spring:
  datasource:
    url: ${PG_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
    schema: ${PG_SCHEMA:pool}
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: ${PG_SCHEMA:pool}
  flyway:
    schemas: ${PG_SCHEMA:pool}
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  servlet:
    context-path: /api/v1
  port: 8080

jwt:
  secret: ${JWT_SECRET:PRh7vkFBAn53ZI2YK5/Y9xaXgGR6sQ3uCUMwO0/x/5Y=}
  expirationTime: ${JWT_EXPIRATION_TIME:86400000}