CREATE TABLE user_info(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);


INSERT INTO user_info (name, phone, email, password, role, created_at, updated_at)
VALUES (
    'Admin',
    '89999999999',
    'admin@example.com',
    '$2a$10$bk3WKgrjQ.KnOAk6oGJYmu/orUTJDeg1iKmSJfGoAsbHsKFoHwmOm',
    'ROLE_ADMIN',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);